server {
    listen 80;
    listen [::]:80;

    # needed for large server imports
    client_max_body_size 10G;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    # block access to all hidden files
    location ~ /\. {
        return 404;
    }

    # login requests do not need to be huge
    location /auth {
        client_max_body_size 1M;
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header Origin $scheme://$host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header Origin $scheme://$host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}