[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
autostart=true

[program:node]
command=/bin/bash /runner.sh
directory=/var/www/server_manager
autostart=true
autorestart=true
user=www-data
stdout_logfile=/var/log/server_manager.log
stderr_logfile=/var/log/server_manager.err
